### ISSUE TITLE
Unable to create or view or debate node

### ISSUE THREAD

**Issue by stpaultim** [OpenKratia/openkratia#6]
I know that you are just getting started and things are supposed to work. But, I thought I'd let you know that some of my attempts to create or view a debate node, generated this error message.

"Unknown data property field_ok_header_image"

**Comment by robertgarrigos** [comment]
Yes, this happens when you access the create debate menu item under admin/content/add content/debate. But normal user would create a debate from within a space content: go to a process or to an assembly, then click on the debates tab and you we'll see two secondary tabs for "debates" list and "add debate".

**Comment by robertgarrigos** [comment]
I see that view the debate gives this error as well. Something triggered this in my last push :-(

**Comment by robertgarrigos** [comment]
Fixed with latest commit https://github.com/OpenKratia/openkratia/commit/686ef6e70192a4c0fa67b8eeea78ae3b3939cf11
